### ISSUE TITLE
[Bug] FWoA v5.1.0 deployment failed

### ISSUE THREAD

**Issue by adcyusuke** [aws-solutions/fhir-works-on-aws#151]
**Describe the bug**
When I tried to deploy the FWoA, the deployment failed due to the error shown below.

> Failed resources:
> fhir-service-dev | 15:17:02 | CREATE_FAILED        | AWS::S3::Bucket                          | fhirLogsBucket (fhirLogsBucket5D12405B) Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: 8E3GYWQVFQGXEE2E; S3 Extended Request ID: L86V77kg6kBTHkhI/B8jYKMEGKDFkzhA3VR5Z0RaxfhU4FPtlmbonpOSRxY03qrYKtmnm5lA9KM/nYNyJPqM4A==; Proxy: null)

**To Reproduce**
Run the command as below:
```
# fhir-works-on-aws-deployment-5.1.0
yarn deploy -c stage=dev -c region=ap-northeast-1
```

**Expected behavior**
Success the deployment

**Versions**
- [FWoA v5.1.0](https://github.com/awslabs/fhir-works-on-aws-deployment/releases/tag/v5.1.0)
- nvm v16.19.0
- yarn v8.6.0
- aws-cdk 2.77.0 (build 06a0b19)

**Additional context**
Is this error related to the article below?
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
If so, do I need to modify the YAML?

**Comment by kcadette** [comment]
Hi @adcyusuke, we have deprecated that version of fhir-works-on-aws. Please follow the instructions [here](https://github.com/aws-solutions/fhir-works-on-aws/blob/main/INSTALL.md) to deploy FWoA.
