### ISSUE TITLE
Unable to Make API call's even using Cognito Token, API Key - Getting UnAuthorized Error

### ISSUE THREAD

**Issue by nkundella** [aws-solutions/fhir-works-on-aws#234]
I have successfully deployed the fhir service in my AWS, however while I try to test even the basic postman calls, I am not able to do it. Getting an UnAuthorized Error. I took the latest code and the error I am receiving is 401 UnAuthorized.

Checked with the Lambda Authorization and have the latest code.

**Screenshots**
![image](https://github.com/aws-solutions/fhir-works-on-aws/assets/107428996/aa46c35a-5ec0-456c-a5a8-62a77871cfdb)

Need a little help on figuring out the missing elements.

**Comment by Bingjiling** [comment]
Hi @nkundella,

Thanks for reaching out! Have you tried the `/metadata` endpoint? The metadata endpoint does not require authorization and can help determine if the server is running properly.

**Comment by nkundella** [comment]
![image](https://github.com/aws-solutions/fhir-works-on-aws/assets/107428996/dfb7aebb-8d45-4acc-acbd-974a7c369097)
For instance, I tried to hit POST account endpoint, and on cloudwatch I see this response and not much information.

**Comment by nkundella** [comment]
![image](https://github.com/aws-solutions/fhir-works-on-aws/assets/107428996/6dd3598f-8bf2-4f97-98db-a861057c397a)

The test within api-gateway fails with same error.

**Comment by nguyen102** [comment]
Did yo include the `x-api-key` in the header? Can you send what the curl command for your request looks like? 

For example this is what mine looks like
```
curl --location '{API_URL}/Account' \
--header 'x-api-key: {API_KEY}' \
--header 'Authorization: Bearer {{COGNITO_TOKEN}}'
```

**Comment by nkundella** [comment]
Here is another snapshot of my curl command 
Provided the following as requested.
1. API Key in the headers for FHIR (From Amazon API Gateway)
2. Provided the url and below is the url we are using (masking the id's)
3. Providing the Bearer Token as well from Cognito.

Please refer the below image.
![image](https://github.com/aws-solutions/fhir-works-on-aws/assets/107428996/078724a5-e438-489a-8270-4dc0cdb5e178)

**Comment by nkundella** [comment]
Which timezone are you working from?
So that, we can have active conversation in a day.

**Comment by nguyen102** [comment]
Hi, can you confirm that you deployed the Cognito version of FWoA? The instructions for deployment are [here](https://github.com/aws-solutions/fhir-works-on-aws/blob/main/INSTALL.md)

This is the command for deploying Cognito version of FWoA.
`cd ./solutions/deployment
rushx deploy --profile <AWS PROFILE> -c stage=<STAGE> -c region=<AWS_REGION>`

Can you go into Cognito and check what groups the Cognito user is in? Is the user in the `practitioner` group?
