### ISSUE TITLE
[Misc] Is this still recommended for one datastore multi tenant?

### ISSUE THREAD

**Issue by masterbater** [aws-solutions/fhir-works-on-aws#235]
**What's on your mind?**
Healthlake has a limit of 10 datastores per region, what if we have thousands of tenants, healthlake charges $0.27 per hour per datastore, I see in migration of FWOA to healthlake the multi tenant is being migrated to different data stores. 
I was thinking on how to achieve one datastore with multi tenant for aws healthlake. I hope you could point me to the right direction.

**Comment by ssvegaraju** [comment]
Hi @masterbater,

We still recommend one tenant per Datastore. However, for HealthLake related questions, it may be better to reach out to the HealthLake team as they have more up-to-date information on Datastores. Additionally, you can reach out to the migration support team at [fwoa-migration-support@amazon.com](mailto:fwoa-migraiton-support@amazon.com) for further support.

Thanks for your time,
Sukeerth
