### ISSUE TITLE
Storing large strings in dynamoDB

### ISSUE THREAD

**Issue by nkundella** [aws-solutions/fhir-works-on-aws#236]
Dear Team,
I hope this message finds you well. I wanted to bring to your attention a challenge we've encountered with our current data storage approach in DynamoDB, specifically regarding the storage of extensions.

As it stands, we store extensions as a separate attribute within DynamoDB. While this approach has generally worked well, we have encountered instances where the string value within extensions exceeds the size limit supported by DynamoDB. A notable example is when we attempt to store a PDF file in base64 format within extensions, which can lead to HTTP 500 errors due to DynamoDB's constraints.

I'd like to initiate a discussion on how we can effectively address this issue. It's crucial that we find a solution to accommodate larger strings within extensions while ensuring data integrity and system performance.

Your input and expertise in this matter are highly valued.

Please let me know your thoughts on this matter, and if anyone has insights or suggestions, don't hesitate to share them. We're collectively invested in finding the best way forward to overcome this challenge.

Thank you for your attention to this matter.

**Comment by ssvegaraju** [comment]
Hi @nkundella,

thanks for raising this issue. Have you considered leveraging Binary resources to store these pdf files? We store the FHIR Resource for Binary Objects in DDB, but put the large binary data within S3. Would this work for your use case? You could then fill the extensions with references to these Binary resources.

Thanks for your time,
Sukeerth

**Comment by nkundella** [comment]
I did think of saving jsons to s3 and using the s3 urls in the extensions to refer back to the pdf files.
But in my case, if there is a case where we want to export the json and give to an organization. We have to get the pdf back from s3 and attach it to the extension and then send the complete json. 
Would that be possible? or is there any other way?

**Comment by ssvegaraju** [comment]
When using Binary resources in FWoA, performing a GET request will return a presigned S3 GET URL from which you can download the pdf from S3, and then attach it back to the json. If you want to avoid using Binary resources and instead store directly in S3, you could construct something similar and use a middleware to get the resource from S3 and attach it to the JSON. However, both of these approaches may increase latency time in requests as there is download time from S3 involved. Does this answer your question?
