### ISSUE TITLE
How to remove opensearch instances from code?

### ISSUE THREAD

**Issue by nkundella** [aws-solutions/fhir-works-on-aws#238]
I deployed the project locally and encountered an unexpected bill totaling $1200 USD due to multiple instances of OpenSearch and approximately $150 USD attributed to Key Management Service (KMS) usage. To mitigate these expenses and avoid future cost overruns, I intend to remove the OpenSearch instances and optimize KMS usage from my codebase. I am seeking guidance on the most effective way to accomplish this while ensuring a seamless redeployment of the project. Any suggestions and best practices for code modification and resource removal are greatly appreciated.

**Comment by Bingjiling** [comment]
Hi @nkundella,

Thanks for reaching out! I'm sorry to hear about the unexpected bill. 

To better assist you with cost reduction, I have a few questions for you. What stage have you deployed FWoA in? How long did the deployed instance run? What functionalities have you tested in the instance? 

As a quick mitigation, you can try deploying FWoA in the dev stage. FWoA is configured to create smaller OpenSearch instance to save on cost in dev stage(Link [code link here](https://github.com/aws-solutions/fhir-works-on-aws/blob/main/solutions/deployment/lib/elasticsearch.ts#L291)). You should see a significant reduce in cost when you deploy FWoA in dev stage instead. 

Thanks,
Yanyu

**Comment by nkundella** [comment]
Thanks for the reply.
I will remove the file today and get back to you.

**Comment by nkundella** [comment]
![image](https://github.com/aws-solutions/fhir-works-on-aws/assets/107428996/694e1fa3-6108-4006-972d-ec5a7855d74f)

I tried to remove all the instances but I get this error when I try to deploy

**Comment by ssvegaraju** [comment]
Hi @nkundella, can I ask what version of FWoA this is using? These look like [CDK Nag](https://github.com/cdklabs/cdk-nag) issues, meaning they are addressable by updating certain properties on resources in the CDK Code. For example, two of the first few issues involve the `fhirLogsBucket` construct and the `glueScriptsBucket` construct not having default encryption enabled. However, this is set as of the latest code [here](https://github.com/aws-solutions/fhir-works-on-aws/blob/main/solutions/deployment/lib/bulkExport.ts#L107).

If you'd like to avoid checking the CDK resources with CDK Nag (not recommended as this may miss best practices for creating AWS resources when customizing FWoA), you can simply disable the checks[ here](https://github.com/aws-solutions/fhir-works-on-aws/blob/main/solutions/deployment/bin/cdk-infra.ts#L103-L146) by commenting them out.

Thanks,
Sukeerth

**Comment by ssvegaraju** [comment]
Hi,

Closing this issue since there hasn't been activity in a while. Feel free to reopen if you have any further questions!

Thanks for your time,
Sukeerth
